ruby '2.7.5'

source 'https://rubygems.org'

gem 'multi_json'

github 'sinatra/sinatra' do
  gem 'sinatra'
  gem 'sinatra-contrib'
end

gem 'bcrypt'
gem 'rake'
gem 'sinatra-activerecord'
gem 'sqlite3'

group :test do
  gem 'rack-test', '2.1.0'
  gem 'rspec'
  gem 'simplecov'
end
